<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/13.0.0">
  <PropertyGroup>
    <RootNamespace>PeepingTom</RootNamespace>
    <Version>1.7.13.1</Version>
    <AssemblyName>PeepingTom</AssemblyName>
  </PropertyGroup>
  <PropertyGroup>
    <DalamudCnLibPath>$(AppData)\XIVLauncherCN\addon\Hooks\dev\</DalamudCnLibPath>
    <DalamudLibPath Condition="$([MSBuild]::IsOSPlatform('Windows')) AND !Exists('$(DalamudLibPath)') AND Exists('$(DalamudCnLibPath)')"
      >$(DalamudCnLibPath)</DalamudLibPath>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources\Language.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Language.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Peeping Tom.Ipc\Peeping Tom.Ipc.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Resources\Language.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Language.resx</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
