<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <RootNamespace>PeepingTom</RootNamespace>
    <Version>2.0.0</Version>
    <AssemblyName>PeepingTom</AssemblyName>
  </PropertyGroup>
  <PropertyGroup>
    <DalamudCnLibPath>$(AppData)\XIVLauncherCN\addon\Hooks\dev\</DalamudCnLibPath>
    <DalamudLibPath Condition="$([MSBuild]::IsOSPlatform('Windows')) AND !Exists('$(DalamudLibPath)') AND Exists('$(DalamudCnLibPath)')"
      >$(DalamudCnLibPath)</DalamudLibPath>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Localization\*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
