//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeepingTom.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PeepingTom.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not close enough to examine..
        /// </summary>
        internal static string ExamineErrorToast {
            get {
                return ResourceManager.GetString("ExamineErrorToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to link, Alt-click to examine, or right click to target..
        /// </summary>
        internal static string MainHelpExamine {
            get {
                return ResourceManager.GetString("MainHelpExamine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to link or right click to target..
        /// </summary>
        internal static string MainHelpNoExamine {
            get {
                return ResourceManager.GetString("MainHelpNoExamine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targeting you.
        /// </summary>
        internal static string MainTargetingYou {
            get {
                return ResourceManager.GetString("MainTargetingYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll frequency in milliseconds.
        /// </summary>
        internal static string SettingsAdvancedPollFrequency {
            get {
                return ResourceManager.GetString("SettingsAdvancedPollFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string SettingsAdvancedTab {
            get {
                return ResourceManager.GetString("SettingsAdvancedTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open examine window on Alt-click.
        /// </summary>
        internal static string SettingsBehaviourExamineEnabled {
            get {
                return ResourceManager.GetString("SettingsBehaviourExamineEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus target on hover.
        /// </summary>
        internal static string SettingsBehaviourFocusHover {
            get {
                return ResourceManager.GetString("SettingsBehaviourFocusHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behaviour.
        /// </summary>
        internal static string SettingsBehaviourTab {
            get {
                return ResourceManager.GetString("SettingsBehaviourTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log alliance members.
        /// </summary>
        internal static string SettingsFilterLogAlliance {
            get {
                return ResourceManager.GetString("SettingsFilterLogAlliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log targeters engaged in combat.
        /// </summary>
        internal static string SettingsFilterLogCombat {
            get {
                return ResourceManager.GetString("SettingsFilterLogCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log party members.
        /// </summary>
        internal static string SettingsFilterLogParty {
            get {
                return ResourceManager.GetString("SettingsFilterLogParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log yourself.
        /// </summary>
        internal static string SettingsFilterLogSelf {
            get {
                return ResourceManager.GetString("SettingsFilterLogSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string SettingsFilterTab {
            get {
                return ResourceManager.GetString("SettingsFilterTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of previous targeters to keep.
        /// </summary>
        internal static string SettingsHistoryAmount {
            get {
                return ResourceManager.GetString("SettingsHistoryAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show previous targeters.
        /// </summary>
        internal static string SettingsHistoryEnabled {
            get {
                return ResourceManager.GetString("SettingsHistoryEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record history when window is closed.
        /// </summary>
        internal static string SettingsHistoryRecordClosed {
            get {
                return ResourceManager.GetString("SettingsHistoryRecordClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string SettingsHistoryTab {
            get {
                return ResourceManager.GetString("SettingsHistoryTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show timestamps.
        /// </summary>
        internal static string SettingsHistoryTimestamps {
            get {
                return ResourceManager.GetString("SettingsHistoryTimestamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark your target.
        /// </summary>
        internal static string SettingsMarkersMarkTarget {
            get {
                return ResourceManager.GetString("SettingsMarkersMarkTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target mark colour.
        /// </summary>
        internal static string SettingsMarkersMarkTargetColour {
            get {
                return ResourceManager.GetString("SettingsMarkersMarkTargetColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark targeting you.
        /// </summary>
        internal static string SettingsMarkersMarkTargeting {
            get {
                return ResourceManager.GetString("SettingsMarkersMarkTargeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targeting mark colour.
        /// </summary>
        internal static string SettingsMarkersMarkTargetingColour {
            get {
                return ResourceManager.GetString("SettingsMarkersMarkTargetingColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targeting mark size.
        /// </summary>
        internal static string SettingsMarkersMarkTargetingSize {
            get {
                return ResourceManager.GetString("SettingsMarkersMarkTargetingSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target mark size.
        /// </summary>
        internal static string SettingsMarkersMarkTargetSize {
            get {
                return ResourceManager.GetString("SettingsMarkersMarkTargetSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markers.
        /// </summary>
        internal static string SettingsMarkersTab {
            get {
                return ResourceManager.GetString("SettingsMarkersTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow moving the main window.
        /// </summary>
        internal static string SettingsWindowAllowMovement {
            get {
                return ResourceManager.GetString("SettingsWindowAllowMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow resizing the main window.
        /// </summary>
        internal static string SettingsWindowAllowResize {
            get {
                return ResourceManager.GetString("SettingsWindowAllowResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open on login.
        /// </summary>
        internal static string SettingsWindowOpenLogin {
            get {
                return ResourceManager.GetString("SettingsWindowOpenLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show window while in combat.
        /// </summary>
        internal static string SettingsWindowShowCombat {
            get {
                return ResourceManager.GetString("SettingsWindowShowCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show window while in cutscenes.
        /// </summary>
        internal static string SettingsWindowShowCutscene {
            get {
                return ResourceManager.GetString("SettingsWindowShowCutscene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show window while in instance.
        /// </summary>
        internal static string SettingsWindowShowInstance {
            get {
                return ResourceManager.GetString("SettingsWindowShowInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        internal static string SettingsWindowTab {
            get {
                return ResourceManager.GetString("SettingsWindowTab", resourceCulture);
            }
        }
        
    }
}
